# Generated by Django 2.2.7 on 2020-11-06 19:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('name', models.CharField(blank=True, max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('network', models.GenericIPAddressField()),
                ('netmask', models.GenericIPAddressField()),
                ('vlan', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(4095)])),
                ('admins', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AddressBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('name', models.CharField(blank=True, max_length=32)),
                ('start', models.GenericIPAddressField()),
                ('length', models.PositiveIntegerField(blank=True, default=16)),
                ('notes', models.TextField(blank=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fractalip.Network')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('name', models.CharField(blank=True, max_length=32)),
                ('address', models.GenericIPAddressField()),
                ('notes', models.TextField(blank=True)),
                ('ipblock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fractalip.AddressBlock')),
            ],
        ),
    ]
